# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10p-8eQ8vXALC6EoxRHES-cLGeqpsoqW9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# [가장 간단하고 확실한 한글 폰트 설정] 코랩 기본 폰트(Malgun Gothic 또는 기본 폰트) 사용
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['axes.unicode_minus'] = False

# 디렉토리 생성
os.makedirs('data', exist_ok=True)
os.makedirs('images', exist_ok=True)

# ---------------------------------------------------------
# 1. 시계열 데이터 생성 (2025년 1년치, 365일)
# ---------------------------------------------------------
np.random.seed(42)
date_range = pd.date_range(start='2025-01-01', end='2025-12-31', freq='D')
n_days = len(date_range)

base_visitors = 150
day_of_week = date_range.dayofweek
dow_effect = np.array([-30, -10, -10, -5, 20, 50, 60])[day_of_week]
month = date_range.month
season_effect = np.where((month == 1) | (month == 2) | (month == 7) | (month == 8), 40, 0)
noise = np.random.normal(0, 15, n_days)

visitors = np.clip(base_visitors + dow_effect + season_effect + noise, 30, 400).astype(int)
checkouts = (visitors * np.random.uniform(1.5, 2.5, n_days)).astype(int)

df = pd.DataFrame({
    'date': date_range,
    'visitors': visitors,
    'checkouts': checkouts
})

# 결측치 및 이상치 의도적 삽입
df.loc[df['date'] == '2025-05-05', 'visitors'] = np.nan
df.loc[df['date'] == '2025-08-15', 'visitors'] = 450

# CSV 저장
df.to_csv('data/library_daily_usage.csv', index=False)

# ---------------------------------------------------------
# 2. 데이터 정제 (결측치 및 이상치 처리)
# ---------------------------------------------------------
df['visitors'] = df['visitors'].interpolate(method='linear')
df['checkouts'] = df['checkouts'].interpolate(method='linear')
df['visitors_MA30'] = df['visitors'].rolling(window=30, min_periods=1).mean()
df['day_name'] = df['date'].dt.day_name()

# ---------------------------------------------------------
# 3. 시각화 및 이미지 저장 (필수 2개 + 권장 1개)
# 영문 레이블을 사용하여 폰트 깨짐 원인 원천 차단
# ---------------------------------------------------------
# [시각화 1] 일별 방문객 트렌드 및 30일 이동평균
plt.figure(figsize=(12, 5))
plt.plot(df['date'], df['visitors'], label='Daily Visitors', color='#aec6cf', alpha=0.6)
plt.plot(df['date'], df['visitors_MA30'], label='30-Day Moving Average', color='#ff6961', linewidth=2.5)
plt.title('2025 Library Daily Visitors Trend', fontsize=13, fontweight='bold')
plt.xlabel('Date')
plt.ylabel('Visitors')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('images/01_visitor_trend.png', dpi=300)
plt.close()

# [시각화 2] 요일별 평균 방문객 분석
dow_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
# 요일 이름을 영어 축약형으로 매핑
df['day_short'] = df['date'].dt.strftime('%a')
dow_avg = df.groupby('day_short')['visitors'].mean().reindex(dow_order)

plt.figure(figsize=(9, 4))
bars = plt.bar(dow_avg.index, dow_avg.values, color='#77dd77')
plt.title('Average Visitors by Day of the Week', fontsize=13, fontweight='bold')
plt.xlabel('Day')
plt.ylabel('Average Visitors')
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 2, f'{int(yval)}', ha='center', va='bottom')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('images/02_weekly_pattern.png', dpi=300)
plt.close()

# [시각화 3] 월별 총 대출 및 방문객 비교
df['month_col'] = df['date'].dt.month
monthly_sum = df.groupby('month_col')[['visitors', 'checkouts']].sum()

plt.figure(figsize=(9, 4))
plt.plot(monthly_sum.index, monthly_sum['visitors'], marker='o', label='Total Visitors', color='#b39eb5')
plt.plot(monthly_sum.index, monthly_sum['checkouts'], marker='s', label='Total Checkouts', color='#ffb347')
plt.title('2025 Monthly Total Visitors and Checkouts', fontsize=13, fontweight='bold')
plt.xlabel('Month')
plt.ylabel('Count')
plt.xticks(range(1, 13))
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('images/03_monthly_seasonality.png', dpi=300)
plt.close()

print("✨ 모든 과정이 경고 없이 깔끔하게 완료되었습니다! 'images/' 폴더를 확인해보세요.")